// apollonian.js -- apollonian packaged as a mountable module.
// start(canvas) returns { stop, pause, resume, reinit, config, params }.
//
// Port of xscreensaver's apollonian.c (Allan R. Wilks, 2000-2001; xscreensaver
// port by David Bagley, 2001). https://www.jwz.org/xscreensaver/
//
// An Apollonian gasket: four mutually-tangent circles are recursively packed
// with ever-smaller tangent circles via Descartes' Circle Theorem. Each circle
// is a (bend, bend*x, bend*y) triple, where bend = curvature = 1/radius and the
// real centre is (x/bend, y/bend). Given three mutually-tangent circles plus a
// fourth that fills their gap, the *opposite* fourth circle has
//     bend4' = 2*(bend1 + bend2 + bend3) - bend4
// and the bend*position coords obey the same linear recurrence -- so the whole
// packing is generated by recursion with NO square roots after the seed, which
// keeps the curvatures exact for integer "games" and numerically tame for the
// few irrational ones. Recursion stops when a circle shrinks below a pixel or
// wanders off-screen. A fresh gasket (a random "game" from a small table of
// integer/irrational seeds, plus generated integer Descartes quadruples) is
// grown, held, then regenerated.
//
// Rendering & timing mirror apollonian.c's draw_apollonian EXACTLY: a fresh game
// is set up by generate() (= init_apollonian, which CLEARS the screen); then the
// gasket is drawn in the C's 5 chunks across 5 frames (frame 0 = the four seed
// circles; frames 1-4 = the four recursive f() fans), HELD until frame `cycles`,
// then a new game regenerates. Inner circles are FILLED (the C's XFillArc); the
// outer bounding circle and the degenerate "lines" are STROKED (XDrawArc /
// XDrawLine). Each chunk's arcs are bucketed by colour index into one Path2D per
// colour (the braid.js / penrose.js idiom) so a fan of thousands of circles is
// only <= ncolors draw calls.

import { makeRandomColormapRGB } from './colormap.js';

export const title = 'apollonian';

export const info = {
  author: 'Allan R. Wilks',
  description: "A fractal packing of circles with smaller circles, demonstrating Descartes's theorem.\n\nhttps://en.wikipedia.org/wiki/Apollonian_gasket\nhttps://en.wikipedia.org/wiki/Descartes%27_theorem",
  year: 2001,
};

export function start(canvas) {
  const ctx = canvas.getContext('2d');

  // Defaults/ranges mirror hacks/config/apollonian.xml 1:1. `delay` is the stock
  // 1 s/frame: the gasket draws in 5 one-second chunks, holds, then regenerates
  // (exactly the C); the slider speeds that up.
  const config = {
    delay: 1000000,  // microseconds between frames (--delay, xml 1000000)
    cycles: 20,      // frames a gasket lives before regenerating (--cycles)
    ncolors: 64,     // size of the make_random_colormap palette (--ncolors)
    label: true,     // draw the integer curvature inside each big circle (--label)
    altgeom: true,   // also relabel some gaskets spherically/hyperbolically (--altgeom)
  };

  // live: true  -> the loop reads config every step (applies instantly).
  // live: false -> the value sizes geometry/colours, so a change re-runs init()
  //                via reinit() (which clears the canvas and re-seeds).
  const params = [
    { key: 'delay', label: 'Frame rate', type: 'range', min: 0, max: 1000000, step: 10000, default: 1000000, unit: ' \u00B5s', invert: true, lowLabel: 'low', highLabel: 'high', live: true },
    { key: 'cycles', label: 'Depth', type: 'range', min: 1, max: 20, step: 1, default: 20, lowLabel: 'shallow', highLabel: 'deep', live: true },
    { key: 'ncolors', label: 'Number of colors', type: 'range', min: 2, max: 255, step: 1, default: 64, lowLabel: 'two', highLabel: 'many', live: false },
    { key: 'label', label: 'Draw labels', type: 'checkbox', default: true, live: false },
    { key: 'altgeom', label: 'Include alternate geometries', type: 'checkbox', default: true, live: false },
  ];

  // ---- Constants from the C ------------------------------------------------
  const K = 2.15470053837925152902;   // 1 + 2/sqrt(3); bound used in dquad()
  const MAXBEND = 100;                 // dquad() search ceiling (C: not user-tunable)
  const BIG = 7;                       // f(): bail if |centre/bend| exceeds this (off-screen)
  const COUNT = 64;                    // # generated integer quadruples (C: *count: 64)
  const MAX_DEPTH = 5000;              // defensive recursion cap (C relies on the bails in f)
  const TWO_PI = Math.PI * 2;

  // The active seed "games" from the C's examples[] (the others are #if 0'd out).
  // Each is four circles as {e, s, h, x, y}: e/s/h = euclidean/spherical/hyperbolic
  // bends, (x, y) = euclidean bend*centre. Game 0 has tabulated s/h; the three
  // irrational games carry s = h = e (the C's table). s/h drive the --altgeom
  // relabelling only; circle positions/radii always use the euclidean e/x/y.
  const DELTA = 2.154700538;   // (3 + 2*sqrt(3)) / 3
  const ALPHA = 2.618033989;   // (3 + sqrt(5)) / 2
  const BETA = 2.890053638;    // PHI + sqrt(PHI), PHI = (1+sqrt(5))/2
  const examples = [
    [ // double semi-bounded (two straight lines + two unit circles)
      { e: 0, s: 0, h: 0, x: 0, y: 1 },
      { e: 0, s: 0, h: 0, x: 0, y: -1 },
      { e: 1, s: 1, h: 1, x: -1, y: 0 },
      { e: 1, s: 1, h: 1, x: 1, y: 0 },
    ],
    [ // 3-fold symmetric bounded (x, y recomputed in generate for game != 0)
      { e: -1, s: -1, h: -1, x: 0, y: 0 },
      { e: DELTA, s: DELTA, h: DELTA, x: 1, y: 0 },
      { e: DELTA, s: DELTA, h: DELTA, x: 1, y: -1 },
      { e: DELTA, s: DELTA, h: DELTA, x: -1, y: 1 },
    ],
    [ // semi-bounded
      { e: 1, s: 1, h: 1, x: 0, y: 0 },
      { e: 0, s: 0, h: 0, x: 0, y: -1 },
      { e: 1 / (ALPHA * ALPHA), s: 1 / (ALPHA * ALPHA), h: 1 / (ALPHA * ALPHA), x: -1, y: 0 },
      { e: 1 / ALPHA, s: 1 / ALPHA, h: 1 / ALPHA, x: -1, y: 0 },
    ],
    [ // unbounded
      { e: 1, s: 1, h: 1, x: 0, y: 0 },
      { e: 1 / (BETA * BETA * BETA), s: 1 / (BETA * BETA * BETA), h: 1 / (BETA * BETA * BETA), x: 1, y: 0 },
      { e: 1 / (BETA * BETA), s: 1 / (BETA * BETA), h: 1 / (BETA * BETA), x: 1, y: 0 },
      { e: 1 / BETA, s: 1 / BETA, h: 1 / BETA, x: 1, y: 0 },
    ],
  ];
  const PREDEF_CIRCLE_GAMES = examples.length;

  // NRAND(n) = uniform integer in [0, n).
  const nrand = (n) => Math.floor(Math.random() * n);

  // The C's enum space { euclidean=0, spherical, hyperbolic } + its caption strings.
  const SPHERICAL = 1;
  const HYPERBOLIC = 2;
  const SPACE_STRINGS = ['euclidean', 'spherical', 'hyperbolic'];

  // ---- State ---------------------------------------------------------------
  let S = 1;                   // devicePixelRatio
  let size, offX, offY;        // pixel mapping: square inscribed in the canvas
  let fontPx, ascent, adSum;   // label metrics (approx X11 "sans-serif bold 16")
  let colorOffset;             // per-gasket hue rotation (C: NRAND(ncolors))
  let c1, c2, c3, c4;          // the four seed circles ({e, s, h, x, y})
  let outerE;                  // = (c1.e >= 0) ? 1 : -c1.e  (the C's `e` scale factor)
  let geometry;                // 0 euclidean / 1 spherical / 2 hyperbolic (--altgeom)
  let labelOn;                 // labels enabled (C: label && c4.e is integer)
  let palette;                 // ncolors 'rgb(r,g,b)' strings, or null when mono
  let mono;                    // ncolors <= 2 -> white circles, B/W labels
  let quads;                   // generated integer Descartes quadruples (lazy)
  let time;                    // the C's cp->time frame counter
  let pending;                 // drawables collected for the current chunk

  // ---- Integer Descartes quadruples (dquad / gcd / isqrt) -------------------

  function gcd(a, b) {
    while (b) { const r = a % b; a = b; b = r; }
    return a;
  }

  // Integer square root, or -1 if n is not a perfect square (matches the C).
  function isqrt(n) {
    if (n < 0) return -1;
    const y = Math.floor(Math.sqrt(n) + 0.5);
    return (n === y * y) ? y : -1;
  }

  // Enumerate the first `n` root integer Descartes quadruples (a, b, c, d) with
  // a <= 0 (stored as -a), exactly the C's dquad().
  function dquad(n) {
    const quad = [];
    for (let a = 0; a < MAXBEND && quad.length < n; a++) {
      const B = Math.trunc(K * a);
      for (let b = a + 1; b <= B && quad.length < n; b++) {
        const C = Math.trunc(((a + b) * (a + b)) / (4.0 * (b - a)));
        for (let c = b; c <= C && quad.length < n; c++) {
          const d = isqrt(b * c - a * (b + c));
          if (d >= 0 && gcd(a, gcd(b, c)) <= 1) {
            quad.push({ a: -a, b: b, c: c, d: -a + b + c - 2 * d });
          }
        }
      }
    }
    // Pad with the canonical (-1, 2, 2, 3) gasket if we found fewer than n.
    while (quad.length < n) quad.push({ a: -1, b: 2, c: 2, d: 3 });
    return quad;
  }

  // ---- Spherical / hyperbolic relabelling (apollonian.c's cquad / geom) ------
  // For a generated integer quadruple, find integer (p,q) = (bend*x, bend*y) for
  // each circle that keep the packing tangent AND admit integer spherical and
  // hyperbolic labels, then set each circle's s/h via geom(). Verbatim transcription
  // of cquad/geom/is_tangent/iceil/iflor + the For/FOR/H/UNIT/T/LO/HI/B macros.
  // This relabels only -- circle positions/radii are unchanged (still euclidean).

  function iflor(a, b) {                       // integer floor division (C's iflor)
    if (b === 0) return 0;
    if (a % b === 0) return a / b;
    const q = Math.trunc(Math.abs(a) / Math.abs(b));
    return ((a < 0) !== (b < 0)) ? -q - 1 : q;
  }

  function iceil(a, b) {                       // integer ceil division (C's iceil)
    if (b === 0) return 0;
    if (a % b === 0) return a / b;
    const q = Math.trunc(Math.abs(a) / Math.abs(b));
    return ((a < 0) !== (b < 0)) ? -q : 1 + q;
  }

  // Two integer circles (e,p,q) are tangent iff dx^2+dy^2 == (e1+e2)^2 (C's is_tangent).
  function isTangent(e1, p1, q1, e2, p2, q2) {
    const dx = p1 * e2 - p2 * e1;
    const dy = q1 * e2 - q2 * e1;
    const s = e1 + e2;
    return dx * dx + dy * dy === s * s;
  }

  // geom(): the spherical (g=-1) / hyperbolic (g=1) label of integer circle (e,p,q).
  function geom(geom_, e, p, q) {
    const g = (geom_ === SPHERICAL) ? -1 : (geom_ === HYPERBOLIC) ? 1 : 0;
    if (g) return (e * e + (1.0 - p * p - q * q) * g) / (2.0 * e);
    return e;
  }

  // cquad: exhaustive integer search; sets C1..C4 .s/.h to the LAST valid placement
  // found (the C does not break, so the innermost tuple wins). If none is found the
  // seeds keep their .s = .h = .e fallback (the C would leave stale values; the
  // euclidean fallback is the safe equivalent). The H()/UNIT()/T() conditions ARE
  // the gating that enforces integer s/h labels -- there is no separate seed reject.
  function cquad(C1, C2, C3, C4) {
    const ea = Math.trunc(C1.e), eb = Math.trunc(C2.e), ec = Math.trunc(C3.e), ed = Math.trunc(C4.e);
    const lopa = ea, loqa = ea, hipa = 0, hiqa = 0;   // outer circle center in {ea..0}^2
    for (let pa = lopa; pa <= hipa; pa++) {
      for (let qa = loqa; qa <= hiqa; qa++) {
        if (!((ea * ea + pa * pa + qa * qa) % 2)) continue;                    // H(a)
        if (!((Math.abs(ea) - 1) * (Math.abs(ea) - 1) >= pa * pa + qa * qa)) continue;  // UNIT(a)
        // B(b); B(c); B(d): per-circle search bounds, scaled off the a-placement.
        const lopb = iceil(eb * (pa + 1), ea) - 1, hipb = iflor(eb * (pa - 1), ea) - 1;
        const loqb = iceil(eb * (qa + 1), ea) - 1, hiqb = iflor(eb * (qa - 1), ea) - 1;
        const lopc = iceil(ec * (pa + 1), ea) - 1, hipc = iflor(ec * (pa - 1), ea) - 1;
        const loqc = iceil(ec * (qa + 1), ea) - 1, hiqc = iflor(ec * (qa - 1), ea) - 1;
        const lopd = iceil(ed * (pa + 1), ea) - 1, hipd = iflor(ed * (pa - 1), ea) - 1;
        const loqd = iceil(ed * (qa + 1), ea) - 1, hiqd = iflor(ed * (qa - 1), ea) - 1;
        for (let pb = lopb; pb <= hipb; pb++) for (let qb = loqb; qb <= hiqb; qb++) {
          if (!((eb * eb + pb * pb + qb * qb) % 2)) continue;                  // H(b)
          if (!isTangent(ea, pa, qa, eb, pb, qb)) continue;                    // T(a,b)
          for (let pc = lopc; pc <= hipc; pc++) for (let qc = loqc; qc <= hiqc; qc++) {
            if (!((ec * ec + pc * pc + qc * qc) % 2)) continue;                // H(c)
            if (!isTangent(ea, pa, qa, ec, pc, qc)) continue;                  // T(a,c)
            if (!isTangent(eb, pb, qb, ec, pc, qc)) continue;                  // T(b,c)
            for (let pd = lopd; pd <= hipd; pd++) for (let qd = loqd; qd <= hiqd; qd++) {
              if (!((ed * ed + pd * pd + qd * qd) % 2)) continue;              // H(d)
              if (!isTangent(ea, pa, qa, ed, pd, qd)) continue;                // T(a,d)
              if (!isTangent(eb, pb, qb, ed, pd, qd)) continue;                // T(b,d)
              if (!isTangent(ec, pc, qc, ed, pd, qd)) continue;                // T(c,d)
              C1.s = geom(SPHERICAL, ea, pa, qa); C1.h = geom(HYPERBOLIC, ea, pa, qa);
              C2.s = geom(SPHERICAL, eb, pb, qb); C2.h = geom(HYPERBOLIC, eb, pb, qb);
              C3.s = geom(SPHERICAL, ec, pc, qc); C3.h = geom(HYPERBOLIC, ec, pc, qc);
              C4.s = geom(SPHERICAL, ed, pd, qd); C4.h = geom(HYPERBOLIC, ed, pd, qd);
            }
          }
        }
      }
    }
  }

  // The bend a circle is labelled/coloured by, per the active geometry (C's p()).
  function geomBend(c) {
    return geometry === SPHERICAL ? c.s : geometry === HYPERBOLIC ? c.h : c.e;
  }

  // ---- Pixel mapping --------------------------------------------------------
  // Map a circle {e, x, y} to screen geometry, replicating apollonian.c's p().
  // Returns {kind:'circle', cx, cy, r} or {kind:'line', ...} or null (degenerate).

  function project(c) {
    const e = outerE;
    if (c.e < 0) {
      // Outer / bounding circle: the C strokes (XDrawArc) using -c1.e as scale.
      const denom = -2.0 * c.e;
      const tlx = size * (-c1.e) * (c.x - 1.0) / denom + size / 2.0 + offX;
      const tly = size * (-c1.e) * (c.y - 1.0) / denom + size / 2.0 + offY;
      const diam = c1.e * size / c.e;   // c1.e<0, c.e<0 -> positive
      return { kind: 'circle', cx: tlx + diam / 2.0, cy: tly + diam / 2.0, r: Math.abs(diam) / 2.0 };
    }
    if (c.e === 0) {
      // Degenerate "circle of infinite radius" = a straight line.
      if (c.x === 0.0 && c.y !== 0.0) {
        const y = (c.y + 1.0) * size / 2.0 + offY;
        return { kind: 'line', x1: 0, y1: y, x2: canvas.width, y2: y };
      }
      if (c.y === 0.0 && c.x !== 0.0) {
        const x = (c.x + 1.0) * size / 2.0 + offX;
        return { kind: 'line', x1: x, y1: 0, x2: x, y2: canvas.height };
      }
      return null;
    }
    // Normal inner circle (C fills via XFillArc).
    const tlx = size * e * (c.x - 1.0) / (2.0 * c.e) + size / 2.0 + offX;
    const tly = size * e * (c.y - 1.0) / (2.0 * c.e) + size / 2.0 + offY;
    const diam = e * size / c.e;
    return { kind: 'circle', cx: tlx + diam / 2.0, cy: tly + diam / 2.0, r: Math.abs(diam) / 2.0 };
  }

  // Colour index from a (geometry-selected) bend g, matching the C:
  // ((int)((g + color_offset) * g)) % ncolors. The C can index pixels[] negatively
  // here for non-euclidean inner circles with negative bend (latent C bug); we wrap
  // into range instead.
  function colorIdxFromBend(g) {
    const n = config.ncolors;
    let ci = Math.trunc((g + colorOffset) * g) % n;
    if (ci < 0) ci += n;
    return ci;
  }

  // ---- Collect one circle's drawable (apollonian.c's p(), minus the draw) ---
  // Pushes a {kind:'disc'|'ring'|'line', ...} into `pending`, plus any label.
  // disc = filled inner circle; ring = stroked outer circle; line = stroked.

  function emit(c) {
    const geo = project(c);
    if (!geo) return;

    // g = the bend the circle is coloured/labelled by, per the active geometry;
    // the C flips it positive only for the outer (c.e < 0) circle.
    let g = geomBend(c);
    if (c.e < 0.0 && g < 0.0) g = -g;
    const ci = colorIdxFromBend(g);

    if (geo.kind === 'line') {
      pending.push({ kind: 'line', x1: geo.x1, y1: geo.y1, x2: geo.x2, y2: geo.y2, ci, label: null, caption: null });
      return;
    }
    if (!isFinite(geo.cx) || !isFinite(geo.cy) || !isFinite(geo.r) || geo.r <= 0) return;

    const outerRing = c.e < 0.0;

    // Labels, matching p(): outer circle gets its (negative) bend near the top-
    // left plus the space-name caption at bottom-left; an inner circle gets its
    // bend centred, in the contrasting colormap entry (idx + ncolors/2), but only
    // when the circle is bigger than the text (C: c.e < e*size/((ascent+descent)*2),
    // i.e. diameter > 2*(ascent+descent)) and the bend < 1000. Labels appear only
    // for all-integer gaskets.
    let label = null;
    let caption = null;
    if (labelOn) {
      if (outerRing) {
        const lx = size * c.x / (2.0 * c.e) + offX + ascent * 2;
        const ly = size * c.y / (2.0 * c.e) + ascent * 4;
        label = { kind: 'outer', text: String(-(g === 0 ? 0 : Math.round(g))), x: lx, y: ly, ci };
        const cap_x = size * c.x / (2.0 * c.e) + offX + ascent * 2;
        const cap_y = size * c.y / (2.0 * c.e) + canvas.height - ascent * 4;
        caption = { text: SPACE_STRINGS[geometry], x: cap_x, y: cap_y, ci };
      } else if (geo.r > adSum && g < 1000.0) {
        const n = config.ncolors;
        let lci = (Math.trunc((g + colorOffset) * g) + Math.floor(n / 2)) % n;
        if (lci < 0) lci += n;
        label = { kind: 'inner', text: String(Math.round(g)), x: geo.cx, y: geo.cy, ci: lci };
      }
    }
    pending.push({ kind: outerRing ? 'ring' : 'disc', cx: geo.cx, cy: geo.cy, r: geo.r, ci, label, caption });
  }

  // ---- The Descartes recursion (apollonian.c's f) ---------------------------
  // Given four mutually-tangent circles, compute the new circle tangent to the
  // first three (opposite the fourth) and recurse three ways. Bail when the new
  // circle is gone (bend 0), sub-pixel (bend > size*outerE), or off-screen.

  function f(a, b, cc, d, depth) {
    if (depth > MAX_DEPTH || pending.length > 300000) return;
    const e = outerE;
    const c = {
      e: 2 * (a.e + b.e + cc.e) - d.e,
      s: 2 * (a.s + b.s + cc.s) - d.s,
      h: 2 * (a.h + b.h + cc.h) - d.h,
      x: 2 * (a.x + b.x + cc.x) - d.x,
      y: 2 * (a.y + b.y + cc.y) - d.y,
    };
    if (c.e === 0 ||
        c.e > size * e ||
        c.x / c.e > BIG || c.y / c.e > BIG ||
        c.x / c.e < -BIG || c.y / c.e < -BIG) {
      return;
    }
    emit(c);
    f(b, cc, c, a, depth + 1);
    f(a, cc, c, b, depth + 1);
    f(a, b, c, cc, depth + 1);
  }

  // ---- Build one fresh gasket (apollonian.c's init_apollonian) --------------

  function randomizeC(r, c) {
    // C's randomize_c: maybe swap x<->y, maybe negate both (a random symmetry).
    if (Math.trunc(r / 2)) { const t = c.x; c.x = c.y; c.y = t; }
    if (r % 2) { c.x = -c.x; c.y = -c.y; }
  }

  function generate() {
    // init_apollonian clears the window, then sets up the seed quadruple.
    ctx.fillStyle = '#000';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    time = 0;
    colorOffset = nrand(config.ncolors);

    // game in [0, PREDEF + COUNT): a predefined example or a generated quad.
    const game = nrand(PREDEF_CIRCLE_GAMES + COUNT);

    // C: altgeom is only effective when labels are on (cp->altgeom = label && altgeom);
    // game 0 stays euclidean. Otherwise pick euclidean / spherical / hyperbolic.
    const effAltgeom = config.label && config.altgeom;
    geometry = (game !== 0 && effAltgeom) ? nrand(3) : 0;

    if (game < PREDEF_CIRCLE_GAMES) {
      const ex = examples[game];
      c1 = { e: ex[0].e, s: ex[0].s, h: ex[0].h, x: ex[0].x, y: ex[0].y };
      c2 = { e: ex[1].e, s: ex[1].s, h: ex[1].h, x: ex[1].x, y: ex[1].y };
      c3 = { e: ex[2].e, s: ex[2].s, h: ex[2].h, x: ex[2].x, y: ex[2].y };
      c4 = { e: ex[3].e, s: ex[3].s, h: ex[3].h, x: ex[3].x, y: ex[3].y };
    } else {
      if (!quads) quads = dquad(COUNT);   // lazily build the integer table once
      const q = quads[game - PREDEF_CIRCLE_GAMES];
      // s/h start = e (euclidean fallback); cquad overwrites them for non-euclidean.
      c1 = { e: q.a, s: q.a, h: q.a, x: 0, y: 0 };
      c2 = { e: q.b, s: q.b, h: q.b, x: 0, y: 0 };
      c3 = { e: q.c, s: q.c, h: q.c, x: 0, y: 0 };
      c4 = { e: q.d, s: q.d, h: q.d, x: 0, y: 0 };
      if (geometry) cquad(c1, c2, c3, c4);   // integer spherical/hyperbolic labels
    }

    // C: labels enabled only when the 4th seed bend is integer (generated games
    // are all-integer, so this just tracks the user toggle for those).
    labelOn = config.label && (c4.e === Math.trunc(c4.e));
    outerE = (c1.e >= 0.0) ? 1.0 : -c1.e;

    // For every game except game 0, recompute the four centres from the bends
    // (the C's q123 construction): exact tangent positions for c1..c4.
    if (game !== 0) {
      if (c1.e === 0.0 || c1.e === -c2.e) return;   // degenerate: leave seeds, regen after `cycles`
      c1.x = 0.0; c1.y = 0.0;
      c2.x = -(c1.e + c2.e) / c1.e; c2.y = 0.0;
      let q123 = Math.sqrt(c1.e * c2.e + c1.e * c3.e + c2.e * c3.e);
      c3.x = (c1.e * c1.e - q123 * q123) / (c1.e * (c1.e + c2.e));
      c3.y = -2.0 * q123 / (c1.e + c2.e);
      q123 = -c1.e - c2.e + q123;
      c4.x = (c1.e * c1.e - q123 * q123) / (c1.e * (c1.e + c2.e));
      c4.y = -2.0 * q123 / (c1.e + c2.e);
    }

    // Random reflections so successive gaskets are not all identically oriented.
    if (Math.random() < 0.5) { c3.y = -c3.y; c4.y = -c4.y; }
    const r = nrand(4);
    randomizeC(r, c1);
    randomizeC(r, c2);
    randomizeC(r, c3);
    randomizeC(r, c4);
  }

  // ---- Render the collected chunk (apollonian.c's actual XFillArc/XDrawArc) --
  // Inner circles are filled, the outer ring + lines stroked, all bucketed by
  // colour into one Path2D each; labels overlaid last.

  function flush() {
    const n = config.ncolors;
    const fillPaths = new Array(n);
    const strokePaths = new Array(n);
    for (const dr of pending) {
      if (dr.kind === 'line') {
        const p = strokePaths[dr.ci] || (strokePaths[dr.ci] = new Path2D());
        p.moveTo(dr.x1, dr.y1);
        p.lineTo(dr.x2, dr.y2);
      } else if (dr.kind === 'ring') {
        const p = strokePaths[dr.ci] || (strokePaths[dr.ci] = new Path2D());
        p.moveTo(dr.cx + dr.r, dr.cy);
        p.arc(dr.cx, dr.cy, dr.r, 0, TWO_PI);
      } else {
        const p = fillPaths[dr.ci] || (fillPaths[dr.ci] = new Path2D());
        p.moveTo(dr.cx + dr.r, dr.cy);
        p.arc(dr.cx, dr.cy, dr.r, 0, TWO_PI);
      }
    }
    for (let i = 0; i < n; i++) {
      if (!fillPaths[i]) continue;
      ctx.fillStyle = mono ? '#fff' : palette[i];
      ctx.fill(fillPaths[i]);
    }
    ctx.lineWidth = Math.max(1, S);
    ctx.lineJoin = 'round';
    for (let i = 0; i < n; i++) {
      if (!strokePaths[i]) continue;
      ctx.strokeStyle = mono ? '#fff' : palette[i];
      ctx.stroke(strokePaths[i]);
    }
    // Labels overlaid after the arcs (the C draws them inline; same result since
    // a packing's circles never overlap, so a label is never covered).
    if (labelOn) {
      ctx.font = 'bold ' + Math.round(fontPx) + 'px sans-serif';
      for (const dr of pending) {
        const lab = dr.label;
        if (!lab) continue;
        if (lab.kind === 'inner') {
          ctx.fillStyle = mono ? '#000' : palette[lab.ci];
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
        } else {
          ctx.fillStyle = mono ? '#fff' : palette[lab.ci];
          ctx.textAlign = 'left';
          ctx.textBaseline = 'alphabetic';
        }
        ctx.fillText(lab.text, lab.x, lab.y);
      }
      // Bottom-left space-name caption ("euclidean"/"spherical"/"hyperbolic"),
      // in the outer ring's colour (C's p(): drawn with the outer circle).
      ctx.textAlign = 'left';
      ctx.textBaseline = 'alphabetic';
      for (const dr of pending) {
        const cap = dr.caption;
        if (!cap) continue;
        ctx.fillStyle = mono ? '#fff' : palette[cap.ci];
        ctx.fillText(cap.text, cap.x, cap.y);
      }
    }
    pending.length = 0;
  }

  // ---- One frame (apollonian.c's draw_apollonian) ---------------------------
  // Frame 0 draws the four seed circles; frames 1-4 each draw one f() fan; the
  // finished gasket then holds until time > cycles, when a fresh game regenerates.

  function step() {
    if (time < 5) {
      pending = [];
      if (time === 0) { emit(c1); emit(c2); emit(c3); emit(c4); }
      else if (time === 1) f(c1, c2, c3, c4, 0);
      else if (time === 2) f(c1, c2, c4, c3, 0);
      else if (time === 3) f(c1, c3, c4, c2, 0);
      else if (time === 4) f(c2, c3, c4, c1, 0);
      flush();
    }
    time++;
    if (time > config.cycles) generate();
  }

  // ---- Init / resize / loop / lifecycle ------------------------------------

  function init() {
    S = window.devicePixelRatio || 1;

    // Square drawing region inscribed in the canvas, centred (C's size/offset).
    size = Math.max(Math.min(canvas.width, canvas.height) - 1, 1);
    offX = (canvas.width - size) / 2;
    offY = (canvas.height - size) / 2;

    // Label metrics: the C loads a fixed "sans-serif bold 16" font; ascent and
    // ascent+descent are approximated (X metrics are unavailable in canvas) and
    // only gate which circles are big enough to label.
    fontPx = 16 * S;
    ascent = fontPx * 0.8;
    adSum = fontPx * 1.2;

    // make_random_colormap(bright_p = False): ncolors INDEPENDENT fully-random
    // RGB colours (NOT a smooth rainbow ramp), exactly the colormap xlockmore
    // builds for apollonian's color_scheme_default. Built ONCE per init; the C
    // builds the colormap at startup and only rotates color_offset per gasket.
    // ncolors <= 2 is the C's mono path (white circles, black/white labels).
    const n = config.ncolors;
    mono = n <= 2;
    palette = mono ? null : makeRandomColormapRGB(n, false).map(([r, g, b]) => `rgb(${r},${g},${b})`);

    pending = [];
    generate();
  }

  function resize() {
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.round(window.innerWidth * dpr);
    canvas.height = Math.round(window.innerHeight * dpr);
    canvas.style.width = window.innerWidth + 'px';
    canvas.style.height = window.innerHeight + 'px';
    ctx.fillStyle = 'black';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    init();
  }

  // Rebuild after a non-live config change (clears the canvas, re-seeds).
  function reinit() {
    ctx.fillStyle = 'black';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    init();
  }

  // rAF lag-accumulator loop: one step() per config.delay (us), banking leftover
  // time so the pace is the same at any refresh rate; cap catch-up so a
  // backgrounded tab can't burst.
  const MAX_CATCHUP_STEPS = 8;
  let lastTime = 0;
  let lag = 0;
  let rafId = 0;

  function frame(now) {
    if (lastTime === 0) lastTime = now;
    lag += now - lastTime;
    lastTime = now;

    const delayMs = config.delay / 1000;
    lag = Math.min(lag, Math.max(delayMs, 1) * MAX_CATCHUP_STEPS);

    let steps = 0;
    while (lag >= delayMs && steps < MAX_CATCHUP_STEPS) {
      step();
      lag -= delayMs;
      steps++;
    }

    rafId = requestAnimationFrame(frame);
  }

  window.addEventListener('resize', resize);
  resize();
  rafId = requestAnimationFrame(frame);

  return {
    stop() {
      cancelAnimationFrame(rafId);
      window.removeEventListener('resize', resize);
    },
    pause() { cancelAnimationFrame(rafId); rafId = 0; },
    resume() { if (!rafId) { lastTime = 0; rafId = requestAnimationFrame(frame); } },
    reinit,   // fresh gasket with the current config
    config,
    params,
  };
}
