// apollonian.js — apollonian packaged as a mountable module.
// start(canvas) returns { stop, pause, resume, reinit, config, params }.
//
// Port of xscreensaver's apollonian.c (Allan R. Wilks, 2000-2001; xscreensaver
// port by David Bagley, 2001). https://www.jwz.org/xscreensaver/
//
// An Apollonian gasket: four mutually-tangent circles are recursively packed
// with ever-smaller tangent circles via Descartes' Circle Theorem. Each circle
// is a (bend, bend*x, bend*y) triple, where bend = curvature = 1/radius and the
// real centre is (x/bend, y/bend). Given three mutually-tangent circles plus a
// fourth that fills their gap, the *opposite* fourth circle has
//     bend4' = 2*(bend1 + bend2 + bend3) - bend4
// and the bend*position coords obey the same linear recurrence — so the whole
// packing is generated by recursion with NO square roots after the seed, which
// keeps the curvatures exact for integer "games" and numerically tame for the
// few irrational ones. Recursion stops when a circle shrinks below a pixel or
// wanders off-screen. A fresh gasket (a random "game" from a small table of
// integer/irrational seeds, plus generated integer Descartes quadruples) is
// grown every `cycles`-derived duration.
//
// Rendering: circles are genuine outlines (thin strokes), not per-pixel accum,
// so this uses canvas VECTOR ops — outlines are bucketed by colour index into
// one Path2D per colour (<= ncolors) and each bucket is stroked once, the
// braid.js / penrose.js idiom (thousands of arcs -> ~ncolors stroke() calls).
// The packing is grown incrementally (a batch of circles per step) so the gasket
// visibly fills in, then holds, then regenerates.

export const title = 'apollonian';

export const info = {
  author: 'Allan R. Wilks',
  description: "A fractal packing of circles with smaller circles, demonstrating Descartes's theorem.",
  year: 2001,
};

export function start(canvas) {
  const ctx = canvas.getContext('2d');

  // Defaults/ranges mirror hacks/config/apollonian.xml (1:1 with the original),
  // except `delay` is tuned much calmer-feeling than the stock 1 s/frame (the C
  // reveals the whole gasket in 5 huge frames; we reveal it smoothly instead).
  const config = {
    delay: 32000,    // microseconds between reveal steps (--delay, xml 1000000)
    cycles: 20,      // "depth" knob; also scales how long a finished gasket holds (--cycles)
    ncolors: 64,     // hue-cycle size the curvature colours are drawn from (--ncolors)
    label: true,     // draw the integer curvature inside each big-enough circle (--label)
  };

  // live: true  -> the loop reads config every step (applies instantly).
  // live: false -> the value sizes geometry/colours/reveal, so a change re-runs
  //                init() via reinit() (which also clears the canvas).
  const params = [
    { key: 'delay', label: 'Frame rate', type: 'range', min: 0, max: 100000, step: 1000, default: 32000, unit: ' \u00B5s', invert: true, lowLabel: 'low', highLabel: 'high', live: true },
    { key: 'cycles', label: 'Depth', type: 'range', min: 1, max: 20, step: 1, default: 20, lowLabel: 'shallow', highLabel: 'deep', live: false },
    { key: 'ncolors', label: 'Colors', type: 'range', min: 1, max: 255, step: 1, default: 64, lowLabel: 'two', highLabel: 'many', live: false },
    { key: 'label', label: 'Draw curvature labels', type: 'checkbox', default: true, live: false },
  ];

  // ---- Constants from the C ------------------------------------------------
  const K = 2.15470053837925152902;   // 1 + 2/sqrt(3); bound used in dquad()
  const MAXBEND = 100;                 // dquad() search ceiling (C: not user-tunable)
  const BIG = 7;                       // f(): bail if |centre/bend| exceeds this (off-screen)
  const COUNT = 64;                    // # generated integer quadruples (C: *count: 64)

  // The active seed "games" from the C's examples[] (the others are #if 0'd out).
  // Each is four circles as {e, x, y}: e = euclidean bend, (x, y) = bend*centre.
  // s/h (spherical/hyperbolic bends) are dropped — this port is euclidean only.
  const DELTA = 2.154700538;   // (3 + 2*sqrt(3)) / 3
  const ALPHA = 2.618033989;   // (3 + sqrt(5)) / 2
  const BETA = 2.890053638;    // PHI + sqrt(PHI), PHI = (1+sqrt(5))/2
  const examples = [
    [ // double semi-bounded (two straight lines + two unit circles)
      { e: 0, x: 0, y: 1 },
      { e: 0, x: 0, y: -1 },
      { e: 1, x: -1, y: 0 },
      { e: 1, x: 1, y: 0 },
    ],
    [ // 3-fold symmetric bounded (x, y recomputed in init for game != 0)
      { e: -1, x: 0, y: 0 },
      { e: DELTA, x: 1, y: 0 },
      { e: DELTA, x: 1, y: -1 },
      { e: DELTA, x: -1, y: 1 },
    ],
    [ // semi-bounded
      { e: 1, x: 0, y: 0 },
      { e: 0, x: 0, y: -1 },
      { e: 1 / (ALPHA * ALPHA), x: -1, y: 0 },
      { e: 1 / ALPHA, x: -1, y: 0 },
    ],
    [ // unbounded
      { e: 1, x: 0, y: 0 },
      { e: 1 / (BETA * BETA * BETA), x: 1, y: 0 },
      { e: 1 / (BETA * BETA), x: 1, y: 0 },
      { e: 1 / BETA, x: 1, y: 0 },
    ],
  ];
  const PREDEF_CIRCLE_GAMES = examples.length;

  // NRAND(n) = uniform integer in [0, n).
  const nrand = (n) => Math.floor(Math.random() * n);

  // ---- State ---------------------------------------------------------------
  let S = 1;                   // devicePixelRatio
  let size, offX, offY;        // pixel mapping: square inscribed in the canvas
  let colorOffset;             // per-gasket hue rotation (C: NRAND(ncolors))
  let c1, c2, c3, c4;          // the four seed circles ({e, x, y})
  let outerE;                  // = (c1.e >= 0) ? 1 : -c1.e  (the C's `e` scale factor)
  let isInt;                   // gasket has all-integer bends (enables labels)
  let palette;                 // ncolors vivid HSL strings
  let quads;                   // generated integer Descartes quadruples (lazy)

  // The grown gasket: a flat list of circles to reveal, each carrying its colour
  // index, screen geometry and (for labels) its integer bend.
  let shapes;                  // [{kind, cx, cy, r, x1,y1,x2,y2, ci, label}]
  let revealed;                // how many of `shapes` have been drawn so far
  let holdSteps;               // remaining hold frames after the gasket is complete

  // ---- Integer Descartes quadruples (dquad / gcd / isqrt) -------------------

  function gcd(a, b) {
    while (b) { const r = a % b; a = b; b = r; }
    return a;
  }

  // Integer square root, or -1 if n is not a perfect square (matches the C).
  function isqrt(n) {
    if (n < 0) return -1;
    const y = Math.floor(Math.sqrt(n) + 0.5);
    return (n === y * y) ? y : -1;
  }

  // Enumerate the first `n` root integer Descartes quadruples (a, b, c, d) with
  // a <= 0 (stored as -a), exactly the C's dquad().
  function dquad(n) {
    const quad = [];
    for (let a = 0; a < MAXBEND && quad.length < n; a++) {
      const B = Math.trunc(K * a);
      for (let b = a + 1; b <= B && quad.length < n; b++) {
        const C = Math.trunc(((a + b) * (a + b)) / (4.0 * (b - a)));
        for (let c = b; c <= C && quad.length < n; c++) {
          const d = isqrt(b * c - a * (b + c));
          if (d >= 0 && gcd(a, gcd(b, c)) <= 1) {
            quad.push({ a: -a, b: b, c: c, d: -a + b + c - 2 * d });
          }
        }
      }
    }
    // Pad with the canonical (-1, 2, 2, 3) gasket if we found fewer than n.
    while (quad.length < n) quad.push({ a: -1, b: 2, c: 2, d: 3 });
    return quad;
  }

  // ---- Pixel mapping --------------------------------------------------------
  // Map a circle {e, x, y} to screen geometry, replicating apollonian.c's p().
  // Returns {kind, cx, cy, r} or {kind:'line', ...} or null (degenerate).

  function project(c) {
    const e = outerE;
    if (c.e < 0) {
      // Outer / bounding circle: the C strokes (XDrawArc) using -c1.e as scale.
      const denom = -2.0 * c.e;
      const tlx = size * (-c1.e) * (c.x - 1.0) / denom + size / 2.0 + offX;
      const tly = size * (-c1.e) * (c.y - 1.0) / denom + size / 2.0 + offY;
      const diam = c1.e * size / c.e;   // c1.e<0, c.e<0 -> positive
      return { kind: 'circle', cx: tlx + diam / 2.0, cy: tly + diam / 2.0, r: Math.abs(diam) / 2.0 };
    }
    if (c.e === 0) {
      // Degenerate "circle of infinite radius" = a straight line.
      if (c.x === 0.0 && c.y !== 0.0) {
        const y = (c.y + 1.0) * size / 2.0 + offY;
        return { kind: 'line', x1: 0, y1: y, x2: canvas.width, y2: y };
      }
      if (c.y === 0.0 && c.x !== 0.0) {
        const x = (c.x + 1.0) * size / 2.0 + offX;
        return { kind: 'line', x1: x, y1: 0, x2: x, y2: canvas.height };
      }
      return null;
    }
    // Normal inner circle (C fills via XFillArc; we stroke its outline).
    const tlx = size * e * (c.x - 1.0) / (2.0 * c.e) + size / 2.0 + offX;
    const tly = size * e * (c.y - 1.0) / (2.0 * c.e) + size / 2.0 + offY;
    const diam = e * size / c.e;
    return { kind: 'circle', cx: tlx + diam / 2.0, cy: tly + diam / 2.0, r: Math.abs(diam) / 2.0 };
  }

  // Colour index for a circle, matching the C: ((int)((g + color_offset) * g)) %
  // ncolors, where g is the (euclidean) bend, made positive for the outer circle.
  function colorIndex(c) {
    let g = c.e;
    if (c.e < 0.0 && g < 0.0) g = -g;
    const n = config.ncolors;
    let ci = Math.trunc((g + colorOffset) * g) % n;
    if (ci < 0) ci += n;
    return ci;
  }

  // Push one circle's drawable into `shapes` (skips degenerate / off-screen).
  function emit(c) {
    const geo = project(c);
    if (!geo) return;
    const ci = colorIndex(c);
    if (geo.kind === 'line') {
      shapes.push({ kind: 'line', x1: geo.x1, y1: geo.y1, x2: geo.x2, y2: geo.y2, ci, label: null });
      return;
    }
    if (!isFinite(geo.cx) || !isFinite(geo.cy) || !isFinite(geo.r) || geo.r <= 0.3) return;
    // Label: the integer bend, drawn only for integer gaskets big enough to fit.
    let label = null;
    if (config.label && isInt) {
      let g = c.e;
      if (c.e < 0.0 && g < 0.0) g = -g;
      label = String(Math.round(g));
    }
    shapes.push({ kind: 'circle', cx: geo.cx, cy: geo.cy, r: geo.r, ci, label });
  }

  // ---- The Descartes recursion (apollonian.c's f) ---------------------------
  // Given four mutually-tangent circles, compute the new circle tangent to the
  // first three (opposite the fourth) and recurse three ways. Bail when the new
  // circle is gone (bend 0), sub-pixel (bend > size*outerE), or off-screen.
  // A hard depth cap guards the (irrational-seed) float cases against stack blow.
  const MAX_DEPTH = 5000;
  function f(a, b, cc, d, depth) {
    if (depth > MAX_DEPTH || shapes.length > 200000) return;
    const e = outerE;
    const c = {
      e: 2 * (a.e + b.e + cc.e) - d.e,
      x: 2 * (a.x + b.x + cc.x) - d.x,
      y: 2 * (a.y + b.y + cc.y) - d.y,
    };
    if (c.e === 0 ||
        c.e > size * e ||
        c.x / c.e > BIG || c.y / c.e > BIG ||
        c.x / c.e < -BIG || c.y / c.e < -BIG) {
      return;
    }
    emit(c);
    f(b, cc, c, a, depth + 1);
    f(a, cc, c, b, depth + 1);
    f(a, b, c, cc, depth + 1);
  }

  // ---- Build one fresh gasket (apollonian.c's init_apollonian) --------------

  function randomizeC(r, c) {
    // C's randomize_c: maybe swap x<->y, maybe negate both (a random symmetry).
    if (Math.trunc(r / 2)) { const t = c.x; c.x = c.y; c.y = t; }
    if (r % 2) { c.x = -c.x; c.y = -c.y; }
  }

  function generate() {
    colorOffset = nrand(config.ncolors);

    // game in [0, PREDEF + COUNT): a predefined example or a generated quad.
    const game = nrand(PREDEF_CIRCLE_GAMES + COUNT);

    if (game < PREDEF_CIRCLE_GAMES) {
      const ex = examples[game];
      c1 = { e: ex[0].e, x: ex[0].x, y: ex[0].y };
      c2 = { e: ex[1].e, x: ex[1].x, y: ex[1].y };
      c3 = { e: ex[2].e, x: ex[2].x, y: ex[2].y };
      c4 = { e: ex[3].e, x: ex[3].x, y: ex[3].y };
    } else {
      if (!quads) quads = dquad(COUNT);   // lazily build the integer table once
      const q = quads[game - PREDEF_CIRCLE_GAMES];
      c1 = { e: q.a, x: 0, y: 0 };
      c2 = { e: q.b, x: 0, y: 0 };
      c3 = { e: q.c, x: 0, y: 0 };
      c4 = { e: q.d, x: 0, y: 0 };
    }

    // Integer gasket iff the seed bends are all integers (enables labels).
    isInt = [c1.e, c2.e, c3.e, c4.e].every((v) => v === Math.trunc(v));
    outerE = (c1.e >= 0.0) ? 1.0 : -c1.e;

    // For every game except game 0, recompute the four centres from the bends
    // (the C's q123 construction): exact tangent positions for c1..c4.
    if (game !== 0) {
      if (c1.e === 0.0 || c1.e === -c2.e) { shapes = []; revealed = 0; holdSteps = 30; return; }
      c1.x = 0.0; c1.y = 0.0;
      c2.x = -(c1.e + c2.e) / c1.e; c2.y = 0.0;
      let q123 = Math.sqrt(c1.e * c2.e + c1.e * c3.e + c2.e * c3.e);
      c3.x = (c1.e * c1.e - q123 * q123) / (c1.e * (c1.e + c2.e));
      c3.y = -2.0 * q123 / (c1.e + c2.e);
      q123 = -c1.e - c2.e + q123;
      c4.x = (c1.e * c1.e - q123 * q123) / (c1.e * (c1.e + c2.e));
      c4.y = -2.0 * q123 / (c1.e + c2.e);
    }

    // Random reflections so successive gaskets are not all identically oriented.
    if (Math.random() < 0.5) { c3.y = -c3.y; c4.y = -c4.y; }
    const r = nrand(4);
    randomizeC(r, c1);
    randomizeC(r, c2);
    randomizeC(r, c3);
    randomizeC(r, c4);

    // Grow the full packing now: the four seeds, then the four recursive fans.
    shapes = [];
    emit(c1); emit(c2); emit(c3); emit(c4);
    f(c1, c2, c3, c4, 0);
    f(c1, c2, c4, c3, 0);
    f(c1, c3, c4, c2, 0);
    f(c2, c3, c4, c1, 0);

    revealed = 0;
    // Hold the finished gasket a while before regenerating; `cycles` (the
    // "depth" knob) scales the hold, so "deep" lingers longer on each packing.
    holdSteps = 0;
  }

  // ---- Drawing --------------------------------------------------------------
  // Reveal `n` more shapes, bucketing circle outlines / lines by colour index
  // into one Path2D each and stroking once per colour (braid.js idiom).

  function drawBatch(from, to) {
    const n = config.ncolors;
    const paths = new Array(n);
    let any = false;
    for (let i = from; i < to; i++) {
      const sObj = shapes[i];
      if (!paths[sObj.ci]) paths[sObj.ci] = new Path2D();
      const p = paths[sObj.ci];
      if (sObj.kind === 'line') {
        p.moveTo(sObj.x1, sObj.y1);
        p.lineTo(sObj.x2, sObj.y2);
      } else {
        p.moveTo(sObj.cx + sObj.r, sObj.cy);
        p.arc(sObj.cx, sObj.cy, sObj.r, 0, Math.PI * 2);
      }
      any = true;
    }
    if (!any) return;
    ctx.lineWidth = Math.max(1, S);
    ctx.lineJoin = 'round';
    for (let i = 0; i < n; i++) {
      if (!paths[i]) continue;
      ctx.strokeStyle = palette[i];
      ctx.stroke(paths[i]);
    }
    // Labels overlaid after the strokes (only the larger circles, integer games).
    for (let i = from; i < to; i++) {
      const sObj = shapes[i];
      if (sObj.kind !== 'circle' || sObj.label === null) continue;
      const fontPx = Math.min(sObj.r, 16 * S);
      if (fontPx < 7 * S) continue;   // too small to read; skip (matches C's gate)
      ctx.fillStyle = '#fff';
      ctx.font = 'bold ' + Math.round(fontPx) + 'px sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(sObj.label, sObj.cx, sObj.cy);
    }
  }

  // ---- One reveal step ------------------------------------------------------

  function step() {
    if (revealed >= shapes.length) {
      // Gasket complete: hold, then regenerate a fresh one.
      if (holdSteps <= 0) {
        // Hold ~ proportional to `cycles` (deeper -> linger longer), in steps.
        holdSteps = 40 + config.cycles * 12;
      }
      if (--holdSteps <= 0) {
        ctx.fillStyle = '#000';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        generate();
      }
      return;
    }
    // Reveal a batch this frame; bigger gaskets reveal faster so growth stays
    // brisk regardless of how many thousand circles the packing has.
    const batch = Math.max(8, Math.ceil(shapes.length / 90));
    const to = Math.min(shapes.length, revealed + batch);
    drawBatch(revealed, to);
    revealed = to;
  }

  // ---- Init / resize / loop / lifecycle ------------------------------------

  function init() {
    S = window.devicePixelRatio || 1;

    // Square drawing region inscribed in the canvas, centred (C's size/offset).
    size = Math.max(Math.min(canvas.width, canvas.height) - 1, 1);
    offX = (canvas.width - size) / 2;
    offY = (canvas.height - size) / 2;

    // Vivid rainbow palette the curvature index selects (white when ncolors<=2,
    // the C's mono path).
    const n = config.ncolors;
    palette = new Array(n);
    for (let i = 0; i < n; i++) palette[i] = n > 2 ? `hsl(${i * 360 / n}, 100%, 50%)` : '#fff';

    generate();
  }

  function resize() {
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.round(window.innerWidth * dpr);
    canvas.height = Math.round(window.innerHeight * dpr);
    canvas.style.width = window.innerWidth + 'px';
    canvas.style.height = window.innerHeight + 'px';
    ctx.fillStyle = 'black';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    init();
  }

  // Rebuild after a non-live config change (clears the canvas, re-seeds).
  function reinit() {
    ctx.fillStyle = 'black';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    init();
  }

  // rAF lag-accumulator loop: one step() per config.delay (µs), banking leftover
  // time so the reveal pace is the same at any refresh rate; cap catch-up so a
  // backgrounded tab can't burst.
  const MAX_CATCHUP_STEPS = 8;
  let lastTime = 0;
  let lag = 0;
  let rafId = 0;

  function frame(now) {
    if (lastTime === 0) lastTime = now;
    lag += now - lastTime;
    lastTime = now;

    const delayMs = config.delay / 1000;
    lag = Math.min(lag, Math.max(delayMs, 1) * MAX_CATCHUP_STEPS);

    let steps = 0;
    while (lag >= delayMs && steps < MAX_CATCHUP_STEPS) {
      step();
      lag -= delayMs;
      steps++;
    }

    rafId = requestAnimationFrame(frame);
  }

  window.addEventListener('resize', resize);
  resize();
  rafId = requestAnimationFrame(frame);

  return {
    stop() {
      cancelAnimationFrame(rafId);
      window.removeEventListener('resize', resize);
    },
    pause() { cancelAnimationFrame(rafId); rafId = 0; },
    resume() { if (!rafId) { lastTime = 0; rafId = requestAnimationFrame(frame); } },
    reinit,   // fresh gasket with the current config
    config,
    params,
  };
}
