// quasicrystal.js -- a DIRECT port of xscreensaver's quasicrystal.c
// (Jamie Zawinski, 2013), self-contained WebGL2. start(canvas) returns
// { stop, pause, resume, reinit, getStats, config, params }.
//
// "Overlapping sine waves create interesting plane-tiling interference
// patterns" (jwz). The .c draws `count` translucent quads, each textured with a
// 1D sine grating, transformed by a per-plane rotator (slow spin + wander) and a
// shared breathing scale, then alpha-blended (alpha = 1/count) into a grayscale
// interference field; a cycling smooth-colormap tints it and a contrast pass
// sharpens it.
//
// This is a LITERAL port of that pipeline, not a re-imagining: the real rotator
// (rotator.js), the real make_smooth_colormap (colormap.js), the real
// transforms, the real 1/count blend and the real `count`/`contrast` params.
// The CPU computes each plane's (cos, sin, wander, scale) every frame exactly as
// the .c does; one fragment shader then evaluates the same per-pixel sum the .c
// produces via blended geometry. Because we drive it from the original's actual
// numbers (texcoord scale = 700/count * pscale, pscale = 1 + 4z, the symmetric
// distribution z = r + i*2pi/count), the fringe DENSITY and the spin/slide
// motion match the original rather than being eyeballed. See quasicrystal.md.
//
// Why a per-pixel shader and not N textured quads: identical result (the .c's
// alpha blend IS a per-pixel weighted sum of the gratings), one pass, and it
// reuses the same overlay-canvas approach as the shadertoy GL hacks.

import { makeYaRandom } from './yarandom.js';
import { makeRotator } from './rotator.js';
import { makeSmoothColormap } from './colormap.js';

export const title = 'quasicrystal';

export const info = {
  author: 'Jamie Zawinski',
  description: 'A quasicrystal is a structure that is ordered but aperiodic.\n\nTwo-dimensional quasicrystals can be generated by adding a set of planes where x is the sine of y. Different complex aperiodic plane tilings are produced depending on the period, position, and rotation of the component planes, and whether the rotation of the planes is evenly distributed around the circle (the "symmetry" option, above) or random.\n\nSee also the "RD-Bomb", "CWaves" and "Penrose" screen savers.\n\nhttps://en.wikipedia.org/wiki/Quasicrystal',
  year: 2013,
};

const MAXP = 37;          // .xml count high (uniform-array bound)
const NCOLORS = 256;      // the .c uses a 256-entry colormap
const OVERHEAD = 37500;   // frame-rate calibration (see framerate-calibration)
const DEF_DELAY = 30000;  // .xml delay default (us) -> base sim rate
const EFF_FPS = 1e6 / (DEF_DELAY + OVERHEAD);   // ~14.8: the original's real rate
const TWIST = 700.0;      // the .c's `scale = 700.0 / count` texcoord span

const VERT = `#version 300 es
void main(){ vec2 v = vec2((gl_VertexID << 1) & 2, gl_VertexID & 2); gl_Position = vec4(v * 2.0 - 1.0, 0.0, 1.0); }`;

const FRAG = `#version 300 es
precision highp float;
precision highp int;
#define MAXP ${MAXP}
uniform vec2  uRes;
uniform vec4  uPlanes[MAXP];   // per plane: (cos th, sin th, wanderX, wanderY)
uniform float uScales[MAXP];   // per plane: texcoord scale (700/count * pscale)
uniform int   uCount;
uniform vec3  uTint;           // brightened cycling colormap entry
uniform float uContrast;       // contrast gain about mid-gray
out vec4 frag;
const float TAU = 6.28318530718;

void main() {
  // Exact screen -> object -> plane mapping from the .c's reshape + draw: the
  // reshape makes it isotropic (1/max(w,h) object-units per pixel, centered),
  // draw's outer glScalef(3) gives the /3, glOrtho(0,1,1,0) flips y. No fudge.
  float m = max(uRes.x, uRes.y);
  vec2 A = vec2(gl_FragCoord.x - 0.5 * uRes.x,
                0.5 * uRes.y - gl_FragCoord.y) / (3.0 * m);

  // Sum the gratings via the .c's exact blend: glBlendFunc(GL_SRC_ALPHA,
  // GL_ONE_MINUS_SRC_ALPHA) with alpha = 1/count over a black clear.
  float a = 1.0 / float(uCount);
  float G = 0.0;
  for (int i = 0; i < MAXP; i++) {
    if (i >= uCount) break;
    vec4 pl = uPlanes[i];
    // S = scale * ( R(-th) * (A - wander) ).x  -- the plane's 1D texcoord here.
    float S = uScales[i] * (pl.x * (A.x - pl.z) + pl.y * (A.y - pl.w));
    G = (0.5 + 0.5 * sin(TAU * S)) * a + G * (1.0 - a);   // 1D sine grating, blended
  }

  // Colorize EXACTLY as the .c: glBlendFunc(GL_DST_COLOR, GL_SRC_COLOR) over the
  // grayscale G == 2 * c' * G, clamped. uTint is the brightened (0.6666 + c/3)
  // cycling colormap entry; the CLAMP is the wash-to-white at bright moments.
  vec3 col = clamp(2.0 * uTint * G, 0.0, 1.0);

  // Contrast EXACTLY as the .c: when contrast > 0, a GL_AND_REVERSE logic op
  // (dst = src & ~dst) on the 8-bit framebuffer, src = gray (1 - contrast/200).
  // A bitwise invert+mask -- inverts the field and posterizes it, not a curve.
  if (uContrast > 0.0) {
    uint c8 = uint((1.0 - uContrast / 200.0) * 255.0);
    uvec3 img8 = uvec3(col * 255.0 + 0.5);
    col = vec3(uvec3(c8) & ~img8) / 255.0;
  }
  frag = vec4(col, 1.0);
}`;

function compile(gl, type, src) {
  const s = gl.createShader(type);
  gl.shaderSource(s, src);
  gl.compileShader(s);
  if (!gl.getShaderParameter(s, gl.COMPILE_STATUS))
    throw new Error('quasicrystal shader: ' + gl.getShaderInfoLog(s));
  return s;
}

export function start(canvas) {
  const config = {
    speed: 1.0,        // playback-rate multiplier on spin/slide/breathe/cycling
    resolution: 1.0,   // render scale vs devicePixelRatio
    count: 17,         // .xml "count" (Density): number of overlapping gratings
    contrast: 30,      // .xml "contrast" (0..100)
    spin: true,        // .xml "spin" (Rotation)
    wander: true,      // .xml "wander" (Displacement)
    // NOTE: the .c default is symmetric=True (evenly-distributed angles -> jwz's
    // regular rosettes). We deliberately default it OFF: independent per-plane
    // angles read as a few grids sliding past each other -- the cooler, more
    // "Hackers (1995)" look (user's call). Toggle Symmetry on for the rosettes.
    symmetric: false,
  };

  const params = [
    { key: 'count', label: 'Density', type: 'range', min: 7, max: 37, step: 1, default: 17, lowLabel: 'few', highLabel: 'many', live: false },
    { key: 'contrast', label: 'Contrast', type: 'range', min: 0, max: 100, step: 1, default: 30, lowLabel: 'low', highLabel: 'high', live: true },
    { key: 'speed', label: 'Speed', type: 'range', min: 0.1, max: 5, step: 0.05, default: 1.0, lowLabel: 'slow', highLabel: 'fast', live: true },
    { key: 'spin', label: 'Rotation', type: 'checkbox', default: true, live: false },
    { key: 'wander', label: 'Displacement', type: 'checkbox', default: true, live: false },
    { key: 'symmetric', label: 'Symmetry', type: 'checkbox', default: false, live: false },   // .c default True; ours False (see config note)
    { key: 'resolution', label: 'Resolution', type: 'range', min: 0.25, max: 1, step: 0.05, default: 1.0, lowLabel: 'fast', highLabel: 'crisp', live: true },
  ];

  // --- overlay canvas (same approach as the shadertoy GL hacks) ---
  const cv = document.createElement('canvas');
  cv.style.cssText = 'position:fixed; inset:0; width:100%; height:100%; z-index:1; pointer-events:none; background:#000;';
  (canvas.parentNode || document.body).appendChild(cv);

  const gl = cv.getContext('webgl2', { alpha: false, antialias: false, depth: false, powerPreference: 'high-performance' });
  if (!gl) {
    console.error('quasicrystal: WebGL2 unavailable.');
    return { stop() { cv.remove(); }, config, params };
  }

  const prog = gl.createProgram();
  gl.attachShader(prog, compile(gl, gl.VERTEX_SHADER, VERT));
  gl.attachShader(prog, compile(gl, gl.FRAGMENT_SHADER, FRAG));
  gl.linkProgram(prog);
  if (!gl.getProgramParameter(prog, gl.LINK_STATUS))
    throw new Error('quasicrystal link: ' + gl.getProgramInfoLog(prog));
  gl.useProgram(prog);
  const vao = gl.createVertexArray();
  gl.bindVertexArray(vao);

  const loc = (n) => gl.getUniformLocation(prog, n);
  const uRes = loc('uRes'), uPlanes = loc('uPlanes'), uScales = loc('uScales'),
        uCount = loc('uCount'), uTint = loc('uTint'), uContrast = loc('uContrast');

  // --- CPU simulation state (rebuilt by reinit / non-live param changes) ---
  let rng, rots, rot2s, colors, ccolor;
  const planeBuf = new Float32Array(MAXP * 4);
  const scaleBuf = new Float32Array(MAXP);

  function build() {
    // The framework seeds yarandom from time/pid (nondeterministic); mirror that.
    rng = makeYaRandom((Math.random() * 0xffffffff) >>> 0);
    const n = config.count;
    rots = [];
    rot2s = [];
    for (let i = 0; i < n; i++) {
      // p->rot  = make_rotator(0,0, spin?0.01:0, 10, wander?0.0001:0, True)
      rots.push(makeRotator({ spinZ: config.spin ? 0.01 : 0, spinAccel: 10, wanderSpeed: config.wander ? 0.0001 : 0, randomize: true }, rng));
      // p->rot2 = make_rotator(0,0,0,0, 0.005, True)  -- the scale breathe
      rot2s.push(makeRotator({ wanderSpeed: 0.005, randomize: true }, rng));
    }
    colors = makeSmoothColormap(rng, NCOLORS);
    ccolor = 0;
  }
  build();

  // Tick every rotator one frame, in the SAME pattern the .c's draw loop reads
  // them (so the motion evolves identically). Then advance the colormap.
  function advanceSim() {
    const n = config.count;
    for (let i = 0; i < n; i++) {
      rots[i].getPosition(true);                        // wander: every plane
      if (!config.symmetric || i === 0) {
        rot2s[i].getPosition(true);                      // pscale source
        rots[i].getRotation(true);                       // rotation source
      }
    }
    ccolor = (ccolor + 1) % NCOLORS;
  }

  // Read current state (no tick) into the GPU uniform buffers.
  function readUniforms() {
    const n = config.count;
    let r = 0, ps0 = 1;
    if (config.symmetric) {
      r = rots[0].getRotation(false).z;
      ps0 = 1 + 4 * rot2s[0].getPosition(false).z;
    }
    for (let i = 0; i < n; i++) {
      const pos = rots[i].getPosition(false);
      const wx = (pos.x - 0.5) * 0.3333;
      const wy = (pos.y - 0.5) * 0.3333;
      let z, ps;
      if (config.symmetric) {
        z = (i === 0) ? r : r + (i * Math.PI * 2 / n);   // even-ish distribution
        ps = ps0;
      } else {
        z = rots[i].getRotation(false).z;
        ps = 1 + 4 * rot2s[i].getPosition(false).z;
      }
      const th = z * 2 * Math.PI;                         // z*360 degrees -> radians
      planeBuf[i * 4 + 0] = Math.cos(th);
      planeBuf[i * 4 + 1] = Math.sin(th);
      planeBuf[i * 4 + 2] = wx;
      planeBuf[i * 4 + 3] = wy;
      scaleBuf[i] = (TWIST / n) * ps;
    }
  }

  function syncSize() {
    const dpr = window.devicePixelRatio || 1;
    const scale = (config.resolution == null ? 1 : config.resolution);
    const w = Math.max(1, Math.round(window.innerWidth * dpr * scale));
    const h = Math.max(1, Math.round(window.innerHeight * dpr * scale));
    if (w !== cv.width || h !== cv.height) { cv.width = w; cv.height = h; gl.viewport(0, 0, w, h); }
  }

  let raf = 0, lastNow = 0, simAcc = 0;
  const stats = { ms: 16 };

  function render(now) {
    syncSize();
    if (lastNow === 0) lastNow = now;
    let dt = now - lastNow;
    lastNow = now;
    if (dt < 0) dt = 0;
    if (dt > 100) dt = 100;
    stats.ms += (dt - stats.ms) * 0.1;

    // Advance the simulation at the original's effective rate (not 60fps).
    simAcc += (dt / 1000) * EFF_FPS * config.speed;
    let guard = 0;
    while (simAcc >= 1 && guard < 8) { advanceSim(); simAcc -= 1; guard++; }
    if (simAcc >= 1) simAcc = 0;   // fell far behind; don't spiral

    readUniforms();
    const n = config.count;
    const c = colors[ccolor];
    gl.useProgram(prog);
    gl.uniform2f(uRes, cv.width, cv.height);
    gl.uniform1i(uCount, n);
    gl.uniform4fv(uPlanes, planeBuf);
    gl.uniform1fv(uScales, scaleBuf);
    // Colorize: the .c brightens the cycling color to 0.6666 + c/3 (a near-white
    // wash), then multiplies the grayscale field by it.
    gl.uniform3f(uTint, 0.6666 + c.r / 3, 0.6666 + c.g / 3, 0.6666 + c.b / 3);
    // contrast passed through 0..100 exactly (the shader does the .c's bitwise op).
    gl.uniform1f(uContrast, config.contrast);

    gl.drawArrays(gl.TRIANGLES, 0, 3);
    raf = requestAnimationFrame(render);
  }

  function onResize() { syncSize(); }
  window.addEventListener('resize', onResize);
  syncSize();
  raf = requestAnimationFrame(render);

  return {
    stop() {
      if (raf) cancelAnimationFrame(raf);
      raf = 0;
      window.removeEventListener('resize', onResize);
      gl.deleteProgram(prog);
      const lose = gl.getExtension('WEBGL_lose_context');
      if (lose) lose.loseContext();
      cv.remove();
    },
    pause() { if (raf) { cancelAnimationFrame(raf); raf = 0; } },
    resume() { if (!raf) { lastNow = 0; raf = requestAnimationFrame(render); } },
    reinit() { build(); },
    getStats() { return { ms: stats.ms, scale: config.resolution, w: cv.width, h: cv.height }; },
    config,
    params,
  };
}
