// thornbird.js — thornbird packaged as a mountable module.
// start(canvas) returns { stop, pause, resume, reinit, config, params }.
//
// Port of xscreensaver's thornbird.c (Tim Auckland, 1997-2002), itself adapted
// from xlockmore's discrete.c. https://www.jwz.org/xscreensaver/
// (Removed from the XScreenSaver distribution as of version 6.05.)
//
// A view of the "Bird in a Thornbush" strange attractor. Each step iterates a
// 2D map a few hundred times, plotting one tiny point per iteration; the map's
// two free parameters (a, c) drift on slow Lissajous curves so the attractor
// continuously morphs, and the whole 3D point cloud is projected through a
// slowly-tumbling viewpoint. A rolling ring buffer keeps the last `cycles`
// frames of points alive — the oldest frame is erased each step — so the figure
// leaves persistent trails whose length (the "Thickness" knob) is that buffer
// depth. The plot colour steps through a fixed palette of random BRIGHT colours
// (the C's make_random_colormap, bright variant — random hue, high saturation
// and value), jumping to a new colour every 1 + cycles/3 steps as the bird
// tumbles. It is NOT a smooth rainbow.
//
// Rendering: thousands of points accumulate over time (cycles * count, e.g.
// 400 * 100 = 40k live points), so this uses the BLIT path — a persistent Uint32
// ImageData buffer that we draw/erase individual pixels into and putImageData
// once per frame, rather than tens of thousands of per-point fillRect calls.

import { makeRandomColormapRGB } from './colormap.js';

export const title = 'thornbird';

export const info = {
  author: 'Tim Auckland',
  description: 'This screen saver was removed from the XScreenSaver distribution as of version 6.05. This fractal is among those generated by "Discrete".',
  year: 2002,
};

export function start(canvas) {
  const ctx = canvas.getContext('2d');

  // Defaults/ranges mirror hacks/config/thornbird.xml 1:1 (delay/count/cycles).
  // thornbird.xml exposes NO ncolors slider; the stock hack hardcodes ncolors=64
  // via its DEFAULTS, so we mirror that as a fixed internal constant (NCOLORS)
  // rather than inventing a UI control the original lacks.
  const config = {
    delay: 10000,   // µs between steps (--delay)
    count: 100,     // points plotted per step (--count, "Points")
    cycles: 400,    // frames of trail kept alive (--cycles, "Thickness")
  };

  const params = [
    { key: 'delay', label: 'Frame rate', type: 'range', min: 0, max: 100000, step: 1000, default: 10000, unit: ' \u00B5s', invert: true, lowLabel: 'low', highLabel: 'high', live: true },
    { key: 'count', label: 'Points', type: 'range', min: 10, max: 1000, step: 10, default: 100, lowLabel: 'few', highLabel: 'many', live: false },
    { key: 'cycles', label: 'Thickness', type: 'range', min: 2, max: 1000, step: 1, default: 400, lowLabel: 'thin', highLabel: 'thick', live: false },
  ];

  const BLACK = 0xFF000000;
  const NCOLORS = 64;   // stock thornbird DEFAULTS *ncolors (not a UI resource)

  let W, H;                   // canvas size (device px)
  let imageData, pixels;      // persistent Uint32 accumulation buffer
  let palette;                // NCOLORS packed-ABGR random bright colours

  // The thornbird map state and the slowly-drifting free parameters.
  let a, b, c, i, j;          // map params + iterate state (a, c vary; b couples)
  let inc;                    // step counter (drives parameter drift + tumble)
  let pix;                    // current palette index
  let scale;                  // point size in device px (1, or 2 on retina)

  // Lissajous frequencies for the a/c parameter drift (chosen once per run).
  let f1, f2;
  // 3D tumbling viewpoint (two angles + their per-step deltas).
  let theta, dtheta, phi, dphi;

  // Ring buffer of the last `cycles` frames; each entry is an Int32Array of
  // interleaved (x, y) pairs (length 2*count) for the `count` points plotted that
  // frame, so we can erase exactly those points when the frame ages out. Coords
  // are stored RAW (possibly off-screen) and plot() clips them, exactly as the C
  // stores raw shorts and lets X clip the XFillRectangles.
  let frames;                 // Array(cycles) of Int32Array(2*count) | null
  let nbuffers;               // == cycles (captured at init)
  let batch;                  // == count (captured at init)

  // Random in [-v/2, +v/2), matching the C's balance_rand().
  function balanceRand(v) {
    return Math.random() * v - v / 2;
  }

  // make_random_colormap(bright_p = True) via colormap.js: NCOLORS INDEPENDENT
  // random "bright" colours — random hue, saturation 30%-99%, value 66%-99% —
  // NOT a smooth rainbow ramp. As the plot index cycles, the colour jumps to a
  // fresh random bright colour. Built ONCE per run (the C builds the colormap at
  // startup and only rotates the index); distribution-faithful via Math.random
  // since the map is re-rolled each run (only the distribution matters).
  function buildPalette() {
    const rgb = makeRandomColormapRGB(NCOLORS, true);   // bright variant
    palette = new Uint32Array(NCOLORS);
    for (let p = 0; p < NCOLORS; p++) {
      const [r, g, b2] = rgb[p];
      // packed 0xFFBBGGRR (little-endian ImageData layout).
      palette[p] = (0xff << 24 | b2 << 16 | g << 8 | r) >>> 0;
    }
  }

  // Paint a scale-by-scale block at (px,py) with packed colour `value`.
  function plot(px, py, value) {
    for (let dy = 0; dy < scale; dy++) {
      const yy = py + dy;
      if (yy < 0 || yy >= H) continue;
      const rowBase = yy * W;
      for (let dx = 0; dx < scale; dx++) {
        const xx = px + dx;
        if (xx < 0 || xx >= W) continue;
        pixels[rowBase + xx] = value;
      }
    }
  }

  // One step == one frame of the C's draw_thornbird: vary a/c + the view, plot
  // `count` fresh points into the current ring slot, erase the slot that is
  // about to be overwritten next, redraw the current slot in this step's colour.
  function step() {
    const erase = (inc + 1) % nbuffers;
    const current = inc % nbuffers;

    // Vary the two free parameters along slow Lissajous curves (verbatim C).
    a = 1.99 + (0.4 * Math.sin(inc / f1) + 0.05 * Math.cos(inc / f2));
    c = 0.80 + (0.15 * Math.cos(inc / f1) + 0.05 * Math.sin(inc / f2));

    // Advance the tumbling viewpoint and cache its sines/cosines.
    theta += dtheta;
    phi += dphi;
    const sint = Math.sin(theta), cost = Math.cos(theta);
    const sinp = Math.sin(phi), cosp = Math.cos(phi);

    // Integer half-extents, matching the C's `maxx / 2` / `maxy / 2` (int div).
    const cx = (W / 2) | 0;
    const cy = (H / 2) | 0;

    // Iterate the attractor `count` times, projecting each point through the
    // tumbling view and recording its raw (x, y) in this frame's slot.
    const buf = (frames[current] && frames[current].length === batch * 2)
      ? frames[current]
      : (frames[current] = new Int32Array(batch * 2));

    for (let k = 0; k < batch; k++) {
      const oldj = j;
      const oldi = i;

      // The "Bird in a Thornbush" map.
      j = oldi;
      i = (1 - c) * Math.cos(Math.PI * a * oldj) + c * b;
      b = oldj;

      // 3D -> 2D projection, then (short) truncation (| 0). Coords are kept RAW
      // (not clamped); plot() clips off-screen points, exactly as the C relies on
      // X to clip the XFillRectangles. (Clamping would pile points on the edges.)
      const x = (cx * (1 + sint * j + cost * cosp * i - cost * sinp * b)) | 0;
      const y = (cy * (1 - cost * j + sint * cosp * i - sint * sinp * b)) | 0;
      buf[2 * k] = x;
      buf[2 * k + 1] = y;
    }

    // Erase the frame that's about to be overwritten next step (paint black).
    const old = frames[erase];
    if (old) {
      for (let k = 0; k < batch; k++) plot(old[2 * k], old[2 * k + 1], BLACK);
    }

    // Pick THIS frame's colour, THEN advance the index for next time: the C sets
    // the GC foreground to MI_PIXEL(pix) BEFORE the conditional `++pix` (jwz's
    // "sooner" cadence: every 1 + cycles/3 steps). Mono (<=2 colours) -> white.
    let value;
    if (palette.length > 2) {
      value = palette[pix];
      if (((inc + 1) % (1 + ((nbuffers / 3) | 0))) === 0) {
        if (++pix >= palette.length) pix = 0;
      }
    } else {
      value = 0xFFFFFFFF;
    }

    // Draw the current frame in the plot colour.
    for (let k = 0; k < batch; k++) plot(buf[2 * k], buf[2 * k + 1], value);

    inc++;
    ctx.putImageData(imageData, 0, 0);
  }

  function init() {
    W = canvas.width;
    H = canvas.height;

    // C bumps the point size on very large (retina) displays.
    scale = (W > 2560 || H > 2560) ? 2 : 1;

    imageData = ctx.createImageData(W, H);
    pixels = new Uint32Array(imageData.data.buffer);
    pixels.fill(BLACK);

    buildPalette();

    // Initial map state (verbatim C): b = 0.1, i = j = 0.1.
    a = 0; c = 0;
    b = 0.1;
    i = 0.1;
    j = 0.1;
    pix = 0;
    inc = 0;

    batch = Math.max(1, Math.round(config.count));
    nbuffers = Math.max(2, Math.round(config.cycles));
    frames = new Array(nbuffers).fill(null);

    // Pick this run's parameter-drift frequencies and tumble rates.
    f1 = Math.floor(Math.random() * 5000);
    f2 = Math.floor(Math.random() * 2000);
    // Guard the C's integer-mod-zero corner so inc/f never divides by zero.
    if (f1 === 0) f1 = 1;
    if (f2 === 0) f2 = 1;

    theta = 0;
    phi = 0;
    dtheta = balanceRand(0.001);
    dphi = balanceRand(0.005);
  }

  function resize() {
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.round(window.innerWidth * dpr);
    canvas.height = Math.round(window.innerHeight * dpr);
    canvas.style.width = window.innerWidth + 'px';
    canvas.style.height = window.innerHeight + 'px';
    init();
  }

  // rAF lag-accumulator paced by config.delay (µs): run one step() per delay,
  // banking leftover time so the pace is identical at any refresh rate. Cap
  // catch-up so a backgrounded tab doesn't fire a burst of steps on refocus.
  //
  // OVERHEAD: the stock delay is a sleep floor; the live binary's real rate is
  // lower (delay + framework overhead — see the framerate-calibration note). The
  // live thornbird measures 41.7 fps (Load 58%, delay-bound = a portable target),
  // but the port at the stock 10000 µs ran 100 steps/sec (2.4x fast). 10000 +
  // 14000 = 24000 µs -> 41.7 steps/sec, matching the live binary. A calibration,
  // not a tuning knob (the config slider still maps 1:1 to the xml delay).
  const OVERHEAD = 14000;
  const MAX_CATCHUP_STEPS = 8;
  let lastTime = 0;
  let lag = 0;
  let rafId = 0;

  function frame(now) {
    if (lastTime === 0) lastTime = now;
    lag += now - lastTime;
    lastTime = now;

    const delayMs = (config.delay + OVERHEAD) / 1000;
    lag = Math.min(lag, delayMs * MAX_CATCHUP_STEPS);

    let steps = 0;
    while (lag >= delayMs && steps < MAX_CATCHUP_STEPS) {
      step();
      lag -= delayMs;
      steps++;
    }

    rafId = requestAnimationFrame(frame);
  }

  // Re-seed with the current config (clears the accumulation buffer because
  // count/cycles resize the ring buffer).
  function reinit() {
    init();
  }

  window.addEventListener('resize', resize);
  resize();
  rafId = requestAnimationFrame(frame);

  return {
    stop() {
      cancelAnimationFrame(rafId);
      window.removeEventListener('resize', resize);
    },
    pause() { cancelAnimationFrame(rafId); rafId = 0; },
    resume() { if (!rafId) { lastTime = 0; rafId = requestAnimationFrame(frame); } },
    reinit,
    config,
    params,
  };
}
