// thornbird.js — thornbird packaged as a mountable module.
// start(canvas) returns { stop, pause, resume, reinit, config, params }.
//
// Port of xscreensaver's thornbird.c (Tim Auckland, 1997-2002), itself adapted
// from xlockmore's discrete.c. https://www.jwz.org/xscreensaver/
// (Removed from the XScreenSaver distribution as of version 6.05.)
//
// A view of the "Bird in a Thornbush" strange attractor. Each step iterates a
// 2D map a few hundred times, plotting one tiny point per iteration; the map's
// two free parameters (a, c) drift on slow Lissajous curves so the attractor
// continuously morphs, and the whole 3D point cloud is projected through a
// slowly-tumbling viewpoint. A rolling ring buffer keeps the last `cycles`
// frames of points alive — the oldest frame is erased each step — so the figure
// leaves persistent trails whose length (the "Thickness" knob) is that buffer
// depth. The plot colour cycles through the rainbow as the bird tumbles.
//
// Rendering: thousands of points accumulate over time (cycles * count, e.g.
// 400 * 100 = 40k live points), so this uses the BLIT path — a persistent Uint32
// ImageData buffer that we draw/erase individual pixels into and putImageData
// once per frame, rather than tens of thousands of per-point fillRect calls.

export const title = 'thornbird';

export const info = {
  author: 'Tim Auckland',
  description: 'This screen saver was removed from the XScreenSaver distribution as of version 6.05. This fractal is among those generated by "Discrete".',
  year: 2002,
};

export function start(canvas) {
  const ctx = canvas.getContext('2d');

  // Defaults/ranges mirror hacks/config/thornbird.xml so the config box maps
  // 1:1 to the original. (`ncolors` isn't in the stock thornbird UI — it
  // hardcodes 64 — but we expose it for parity with the other ports.)
  const config = {
    delay: 10000,   // µs between steps (--delay)
    count: 100,     // points plotted per step (--count, "Points")
    cycles: 400,    // frames of trail kept alive (--cycles, "Thickness")
    ncolors: 64,    // size of the rainbow palette (--ncolors)
  };

  const params = [
    { key: 'delay', label: 'Frame rate', type: 'range', min: 0, max: 100000, step: 1000, default: 10000, unit: ' \u00B5s', invert: true, lowLabel: 'low', highLabel: 'high', live: true },
    { key: 'count', label: 'Points', type: 'range', min: 10, max: 1000, step: 10, default: 100, lowLabel: 'few', highLabel: 'many', live: false },
    { key: 'cycles', label: 'Thickness', type: 'range', min: 2, max: 1000, step: 1, default: 400, lowLabel: 'thin', highLabel: 'thick', live: false },
    { key: 'ncolors', label: 'Colors', type: 'range', min: 1, max: 255, step: 1, default: 64, lowLabel: 'two', highLabel: 'many', live: false },
  ];

  const BLACK = 0xFF000000;

  let W, H, S;                // canvas size (device px) and devicePixelRatio
  let imageData, pixels;      // persistent Uint32 accumulation buffer
  let palette;                // ncolors packed-ABGR rainbow values

  // The thornbird map state and the slowly-drifting free parameters.
  let a, b, c, i, j;          // map params + iterate state (a, c vary; b couples)
  let inc;                    // step counter (drives parameter drift + tumble)
  let pix;                    // current palette index
  let scale;                  // point size in device px (1, or 2 on retina)

  // Lissajous frequencies for the a/c parameter drift (chosen once per run).
  let f1, f2;
  // 3D tumbling viewpoint (two angles + their per-step deltas).
  let theta, dtheta, phi, dphi;

  // Ring buffer of the last `cycles` frames; each entry is an Int32Array of
  // packed pixel indices (y*W + x) for the `count` points plotted that frame,
  // so we can erase exactly those pixels when the frame ages out.
  let frames;                 // Array(cycles) of Int32Array(count) | null
  let nbuffers;               // == cycles (captured at init)
  let batch;                  // == count (captured at init)

  // Random in [-v/2, +v/2), matching the C's balance_rand().
  function balanceRand(v) {
    return Math.random() * v - v / 2;
  }

  function buildPalette() {
    const n = Math.max(1, Math.round(config.ncolors));
    palette = new Uint32Array(n);
    for (let p = 0; p < n; p++) {
      // hsl(h,100%,50%) -> packed 0xFFBBGGRR (little-endian ImageData layout).
      const [r, g, b2] = hslToRgb(p / n, 1, 0.5);
      palette[p] = (0xff << 24 | b2 << 16 | g << 8 | r) >>> 0;
    }
  }

  // hsl (h in [0,1)) -> [r,g,b] each 0-255.
  function hslToRgb(h, s, l) {
    const c2 = (1 - Math.abs(2 * l - 1)) * s;
    const x = c2 * (1 - Math.abs(((h * 6) % 2) - 1));
    const m = l - c2 / 2;
    let r = 0, g = 0, b2 = 0;
    const seg = Math.floor(h * 6) % 6;
    if (seg === 0) { r = c2; g = x; }
    else if (seg === 1) { r = x; g = c2; }
    else if (seg === 2) { g = c2; b2 = x; }
    else if (seg === 3) { g = x; b2 = c2; }
    else if (seg === 4) { r = x; b2 = c2; }
    else { r = c2; b2 = x; }
    return [
      Math.round((r + m) * 255),
      Math.round((g + m) * 255),
      Math.round((b2 + m) * 255),
    ];
  }

  // Paint a scale-by-scale block at (px,py) with packed colour `value`.
  function plot(px, py, value) {
    for (let dy = 0; dy < scale; dy++) {
      const yy = py + dy;
      if (yy < 0 || yy >= H) continue;
      const rowBase = yy * W;
      for (let dx = 0; dx < scale; dx++) {
        const xx = px + dx;
        if (xx < 0 || xx >= W) continue;
        pixels[rowBase + xx] = value;
      }
    }
  }

  // One step == one frame of the C's draw_thornbird: vary a/c + the view, plot
  // `count` fresh points into the current ring slot, erase the slot that is
  // about to be overwritten next, redraw the current slot in this step's colour.
  function step() {
    const erase = (inc + 1) % nbuffers;
    const current = inc % nbuffers;

    // Vary the two free parameters along slow Lissajous curves (verbatim C).
    a = 1.99 + (0.4 * Math.sin(inc / f1) + 0.05 * Math.cos(inc / f2));
    c = 0.80 + (0.15 * Math.cos(inc / f1) + 0.05 * Math.sin(inc / f2));

    // Advance the tumbling viewpoint and cache its sines/cosines.
    theta += dtheta;
    phi += dphi;
    const sint = Math.sin(theta), cost = Math.cos(theta);
    const sinp = Math.sin(phi), cosp = Math.cos(phi);

    // Iterate the attractor `count` times, projecting each point to the screen
    // and recording its pixel index in this frame's slot.
    const buf = (frames[current] && frames[current].length === batch)
      ? frames[current]
      : (frames[current] = new Int32Array(batch));

    for (let k = 0; k < batch; k++) {
      const oldj = j;
      const oldi = i;

      // The "Bird in a Thornbush" map.
      j = oldi;
      i = (1 - c) * Math.cos(Math.PI * a * oldj) + c * b;
      b = oldj;

      // 3D -> 2D projection through the tumbling view (matches the C exactly).
      let x = (W / 2 * (1 + sint * j + cost * cosp * i - cost * sinp * b)) | 0;
      let y = (H / 2 * (1 - cost * j + sint * cosp * i - sint * sinp * b)) | 0;

      // Clamp the top-left so a `scale`-sized block stays in bounds for indexing.
      if (x < 0) x = 0; else if (x > W - scale) x = W - scale;
      if (y < 0) y = 0; else if (y > H - scale) y = H - scale;

      buf[k] = y * W + x;
    }

    // Erase the frame that's about to be overwritten next step (paint black).
    const old = frames[erase];
    if (old) {
      for (let k = 0; k < old.length; k++) {
        const base = old[k];
        const ex = base % W, ey = (base / W) | 0;
        plot(ex, ey, BLACK);
      }
    }

    // Cycle the plot colour (C: every 1 + cycles/3 increments — "sooner" jwz).
    if (palette.length > 2) {
      if (((inc + 1) % (1 + ((nbuffers / 3) | 0))) === 0) {
        if (++pix >= palette.length) pix = 0;
      }
    } else {
      pix = 0;
    }
    const value = palette.length > 2 ? palette[pix] : 0xFFFFFFFF;

    // Draw the current frame in the plot colour.
    for (let k = 0; k < batch; k++) {
      const base = buf[k];
      plot(base % W, (base / W) | 0, value);
    }

    inc++;
    ctx.putImageData(imageData, 0, 0);
  }

  function init() {
    S = window.devicePixelRatio || 1;
    W = canvas.width;
    H = canvas.height;

    // C bumps the point size on very large (retina) displays.
    scale = (W > 2560 || H > 2560) ? 2 : 1;

    imageData = ctx.createImageData(W, H);
    pixels = new Uint32Array(imageData.data.buffer);
    pixels.fill(BLACK);

    buildPalette();

    // Initial map state (verbatim C): b = 0.1, i = j = 0.1.
    a = 0; c = 0;
    b = 0.1;
    i = 0.1;
    j = 0.1;
    pix = 0;
    inc = 0;

    batch = Math.max(1, Math.round(config.count));
    nbuffers = Math.max(2, Math.round(config.cycles));
    frames = new Array(nbuffers).fill(null);

    // Pick this run's parameter-drift frequencies and tumble rates.
    f1 = Math.floor(Math.random() * 5000);
    f2 = Math.floor(Math.random() * 2000);
    // Guard the C's integer-mod-zero corner so inc/f never divides by zero.
    if (f1 === 0) f1 = 1;
    if (f2 === 0) f2 = 1;

    theta = 0;
    phi = 0;
    dtheta = balanceRand(0.001);
    dphi = balanceRand(0.005);
  }

  function resize() {
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.round(window.innerWidth * dpr);
    canvas.height = Math.round(window.innerHeight * dpr);
    canvas.style.width = window.innerWidth + 'px';
    canvas.style.height = window.innerHeight + 'px';
    init();
  }

  // rAF lag-accumulator paced by config.delay (µs): run one step() per delay,
  // banking leftover time so the pace is identical at any refresh rate. Cap
  // catch-up so a backgrounded tab doesn't fire a burst of steps on refocus.
  const MAX_CATCHUP_STEPS = 8;
  let lastTime = 0;
  let lag = 0;
  let rafId = 0;

  function frame(now) {
    if (lastTime === 0) lastTime = now;
    lag += now - lastTime;
    lastTime = now;

    const delayMs = config.delay / 1000;
    lag = Math.min(lag, delayMs * MAX_CATCHUP_STEPS);

    let steps = 0;
    while (lag >= delayMs && steps < MAX_CATCHUP_STEPS) {
      step();
      lag -= delayMs;
      steps++;
    }

    rafId = requestAnimationFrame(frame);
  }

  // Re-seed with the current config (clears the accumulation buffer because
  // count/cycles/colors resize the ring and palette).
  function reinit() {
    init();
  }

  window.addEventListener('resize', resize);
  resize();
  rafId = requestAnimationFrame(frame);

  return {
    stop() {
      cancelAnimationFrame(rafId);
      window.removeEventListener('resize', resize);
    },
    pause() { cancelAnimationFrame(rafId); rafId = 0; },
    resume() { if (!rafId) { lastTime = 0; rafId = requestAnimationFrame(frame); } },
    reinit,
    config,
    params,
  };
}
