#!/usr/bin/env node
// convert-teapot.mjs -- extract the Utah-teapot Bezier control data from
// xscreensaver-6.15/hacks/glx/teapot.c into a verbatim JS data module
// (hacks/teapot-data.js). hacks/teapot.js ports the evaluator (unit_teapot's
// HAVE_GLMAP path) that turns this control net into a triangle mesh.
//
// Two arrays: patchdata[10][16] (control-point indices for the 10 base patches:
// rim, body x2, lid x2, bottom, handle x2, spout x2) and cpdata[][3] (the
// control points). Copied as verbatim numeric tokens.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, '..', 'xscreensaver-6.15', 'hacks', 'glx', 'teapot.c');
const OUT = join(here, '..', 'hacks', 'teapot-data.js');

const src = readFileSync(SRC, 'utf8');

function body(decl) {
  // grab from `decl ... = {` to the matching top-level `};` (rows use nested {}).
  const start = src.indexOf(decl);
  if (start < 0) throw new Error('not found: ' + decl);
  const open = src.indexOf('{', start);
  let depth = 0, i = open;
  for (; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') { depth--; if (depth === 0) break; }
  }
  return src.slice(open + 1, i);
}

const ints = (s) => (s.match(/-?\d+/g) || []).map((t) => parseInt(t, 10));
const floats = (s) => (s.match(/-?\d+\.?\d*(?:[eE][-+]?\d+)?/g) || []);

const patch = ints(body('patchdata[][16]'));
const cp = floats(body('cpdata[][3]'));

if (patch.length !== 10 * 16) throw new Error(`patchdata: ${patch.length} ints, expected 160`);
if (cp.length % 3 !== 0) throw new Error(`cpdata: ${cp.length} floats, not a multiple of 3`);

const wrapInts = (arr, per) => {
  const lines = [];
  for (let i = 0; i < arr.length; i += per) lines.push('  [' + arr.slice(i, i + per).join(', ') + ']');
  return lines.join(',\n');
};
const wrapFloats = (arr, per) => {
  const lines = [];
  for (let i = 0; i < arr.length; i += per) lines.push('  [' + arr.slice(i, i + per).join(', ') + ']');
  return lines.join(',\n');
};

const out = `// teapot-data.js -- GENERATED by tools/convert-teapot.mjs from
// xscreensaver-6.15/hacks/glx/teapot.c. Do not edit by hand; re-run the tool.
//
// The Utah-teapot Bezier control net (Martin Newell / SGI), verbatim. patchdata
// indexes into cpdata for the 10 base 4x4 patches; hacks/teapot.js evaluates them
// (with the y / x reflections) into a mesh, exactly as teapot.c's unit_teapot.

export const patchdata = [
${wrapInts(patch, 16)},
];

export const cpdata = [
${wrapFloats(cp, 3)},
];
`;

writeFileSync(OUT, out);
console.log('wrote', OUT, '-- patches:', patch.length / 16, 'control points:', cp.length / 3);
